name: Release-Executable

# Pyinstaller requires that executables for each OS are built on that OS
# This action is intended to build on each of the supported OS's: mac, windows, linux.
# and then upload all three files to a new release

# reference material:
# https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions
# https://anshumanfauzdar.medium.com/using-github-actions-to-bundle-python-application-into-a-single-package-and-automatic-release-834bd42e0670

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  buildexe:
    name: Build executables and upload them to the existing release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: >
              pyinstaller tabcmd-windows.spec --clean --noconfirm --distpath ./dist/windows
            OUT_FILE_NAME: tabcmd.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable


    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies and build
      run: |
        echo ${{github.ref_name}}
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        pip install .
        pip install .[package]
        doit version
        python -m build

    - name: Package with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}

    - name: Validate package for ${{matrix.TARGET}}
      run: ./dist/${{ matrix.TARGET }}/${{matrix.OUT_FILE_NAME}}

    - uses: actions/upload-artifact@v3
      with:
        path: ./dist/${{ matrix.TARGET }}/${{ matrix.OUT_FILE_NAME }}/
